---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-repo-source-git-test
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/seemhelawar15/fluxCD-repo/tree/main/Kubernetes-Manifests-file/Frontend
