apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: hello-world:latest
        imagePullPolicy: Always
     
